language:
  - java

services:
  - mysql

env:
- DB=mysql

sudo: false

before_script:
  - "ls"
  - "mysql -u root -e 'script Auth/src/main/resources/db.sql'"

script:
  - "cd Auth"
  - "mvn jetty:run &"
  - "cd .."
  - "cd Tests"
  - "python FullAuthTest.py"
