language:
  - java

services:
  - mysql

env:
- DB=mysql

sudo: false

install:
  - mvn test

before_script:
  - "./setup.sh"

script:
  - "cd Auth"
  - "mvn jetty:run &"
  - "python FullAuthTest.py"
