language:
  - java

services:
  - mysql

env:
- DB=mysql

sudo: true

before_script:
  - "mysql -u root -e 'source /home/travis/build/JonLMyers/Skitter/Auth/src/main/resources/db.sql'"

script:
  - sudo iptables -F
  - sudo iptables -X
  - sudo iptables -t nat -F
  - sudo iptables -t nat -X
  - sudo iptables -t mangle -F
  - sudo iptables -t mangle -X
  - sudo iptables -P INPUT ACCEPT
  - sudo iptables -P OUTPUT ACCEPT
  - sudo iptables -P FORWARD ACCEPT
  - "cd Auth"
  - "pwd"
  - "mvn jetty:run &"
  - "cd .."
  - "cd Tests"
  - "python FullAuthTest.py"
