language:
  - java

services:
  - mysql

env:
- DB=mysql

sudo: false

before_script:
  - "mysql -u root -e 'source /home/travis/build/JonLMyers/Skitter/Auth/src/main/resources/db.sql'"

script:
  - iptables -F
  - iptables -X
  - iptables -t nat -F
  - iptables -t nat -X
  - iptables -t mangle -F
  - iptables -t mangle -X
  - iptables -P INPUT ACCEPT
  - iptables -P OUTPUT ACCEPT
  - iptables -P FORWARD ACCEPT
  - "cd Auth"
  - "pwd"
  - "mvn jetty:run &"
  - "cd .."
  - "cd Tests"
  - "python FullAuthTest.py"
