language:
  - java

services:
  - mysql

env:
- DB=mysql

sudo: false

before_script:
- "mysql -u root -e
  'CREATE DATABASE  IF NOT EXISTS `accounts`;
  USE `accounts`;
  DROP TABLE IF EXISTS `role`;
  CREATE TABLE `role` (`id` int(11) NOT NULL AUTO_INCREMENT,`name` varchar(45) DEFAULT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
  LOCK TABLES `role` WRITE;
  INSERT INTO `role` VALUES (1,'ROLE_USER');
  UNLOCK TABLES;
  DROP TABLE IF EXISTS `user`;
  CREATE TABLE `user` (`id` int(11) NOT NULL AUTO_INCREMENT,`screenName` VARCHAR (255) DEFAULT NULL,`username` varchar(255) DEFAULT NULL,`password` varchar(255) DEFAULT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
  DROP TABLE IF EXISTS `user_role`;
  CREATE TABLE `user_role` (`user_id` int(11) NOT NULL,`role_id` int(11) NOT NULL,PRIMARY KEY (`user_id`,`role_id`),KEY `fk_user_role_roleid_idx` (`role_id`),CONSTRAINT `fk_user_role_roleid` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `fk_user_role_userid` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8;'"


script:
  - "cd Auth"
  - "mvn jetty:run &"
  - "python FullAuthTest.py"
